# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import math
from cmath import cos

import matplotlib.pyplot as plt
from PIL import Image
from PySide6.QtCore import QCoreApplication, QDate, QDateTime, QLine, QLineF, QLocale, QMetaObject, QObject, QPoint, QRect, QSize, Qt, QTime, QUrl  # NOQA
from PySide6.QtGui import QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QGradient, QIcon, QImage, QKeySequence, QLinearGradient, QPaintDevice, QPainter, QPalette, QPen, QPixmap, QRadialGradient, QTransform  # NOQA
from PySide6.QtWidgets import QApplication, QGraphicsPixmapItem, QGraphicsScene, QGraphicsView, QLabel, QLineEdit, QPushButton, QSizePolicy, QWidget  # NOQA
from sqlalchemy import create_engine

import satellite_images
from utm.conversion import from_latlon


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.resize(800, 600)
        self.pushButton = QPushButton(Widget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(550, 20, 211, 41))
        #self.pushButton.clicked.connect(self.loadReceiverData)
        self.lineEdit = QLineEdit(Widget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(550, 110, 161, 31))
        self.lineEdit_2 = QLineEdit(Widget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(550, 170, 161, 31))
        self.lineEdit_3 = QLineEdit(Widget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(550, 230, 161, 31))
        self.lineEdit_4 = QLineEdit(Widget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(550, 490, 211, 31))
        self.lineEdit_5 = QLineEdit(Widget)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(550, 430, 211, 31))
        self.lineEdit_6 = QLineEdit(Widget)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(550, 370, 211, 31))
        self.label = QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(550, 90, 111, 16))
        self.label_2 = QLabel(Widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(550, 150, 111, 16))
        self.label_3 = QLabel(Widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(550, 210, 111, 16))
        self.label_4 = QLabel(Widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(550, 350, 191, 16))
        self.label_5 = QLabel(Widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(550, 410, 191, 16))
        self.label_6 = QLabel(Widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(550, 470, 191, 16))
        self.graphicsView = QGraphicsView(Widget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(30, 20, 501, 501))
        # self.graphicsScene = QGraphicsScene(Widget)
        # self.graphicsScene.setObjectName(u"graphicsScene")
        self.lineEdit_7 = QLineEdit(Widget)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(720, 110, 61, 31))
        self.lineEdit_8 = QLineEdit(Widget)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(720, 170, 61, 31))
        self.lineEdit_9 = QLineEdit(Widget)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(720, 230, 61, 31))
        self.label_7 = QLabel(Widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(720, 90, 111, 16))
        self.label_8 = QLabel(Widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(720, 150, 111, 16))
        self.label_9 = QLabel(Widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(720, 210, 111, 16))

        self.label_10 = QLabel(Widget)
        self.label_10.setGeometry(QRect(30, 20, 501, 501))
        self.label_10.setObjectName(u"label_10")

        self.label_11 = QLabel(Widget)
        self.label_11.setGeometry(QRect(30, 20, 200, 200))
        self.label_11.setObjectName(u"label_11")

        self.label_12 = QLabel(Widget)
        self.label_12.setGeometry(QRect(60, 20, 200, 200))
        self.label_12.setObjectName(u"label_12")

        self.label_13 = QLabel(Widget)
        self.label_13.setGeometry(QRect(90, 20, 200, 200))
        self.label_13.setObjectName(u"label_13")

        #self.line_1 = QLine(0,0,50,50)

        
        

        self.pushButton.clicked.connect(self.loadReceiverData)
        #self.pushButton.clicked.connect(self.paintEvent)
        


        self.retranslateUi(Widget)

    
        
        

        

        

        

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.pushButton.setText(QCoreApplication.translate("Widget", u"Start", None))
        self.label.setText(QCoreApplication.translate("Widget", u"Receiver 1 Location", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"Receiver 2 Location", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"Receiver 3 Location", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"Expected Transmitter Location", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"Calculated Transmitter Location", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"Error", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"Angle 1", None))
        self.label_8.setText(QCoreApplication.translate("Widget", u"Angle 2", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"Angle 3", None))
        self.label_10.setText(QCoreApplication.translate("Widget", u"", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"", None))
        self.label_12.setText(QCoreApplication.translate("Widget", u"", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"", None))
        

    def loadReceiverData(self):
        # print("bangerr")
        engine = create_engine('postgresql+psycopg2://postgres:nyhr7fv245@localhost:5432/rec403')

        check_query = "SELECT * FROM recdata"

        with engine.connect() as con:
            names = con.execute(check_query).scalars(0).all()
            lats = con.execute(check_query).scalars(1).all()
            longs = con.execute(check_query).scalars(2).all()
            trans_lats = con.execute(check_query).scalars(3).all()
            trans_longs = con.execute(check_query).scalars(4).all()
            angles = con.execute(check_query).scalars(5).all()

        lats_longs = [None]*(len(lats)+len(longs))
        lats_longs[::2] = lats
        lats_longs[1::2] = longs

        trans_lats_longs = str(trans_lats[0])+str(trans_longs[0])

        lats_longs[0] = str(lats_longs[0])+ "," +str(lats_longs[1])
        lats_longs[1] = str(lats_longs[2])+ "," +str(lats_longs[3])
        lats_longs[2] = str(lats_longs[4])+ "," +str(lats_longs[5])

        self.lineEdit.setText(lats_longs[0])
        self.lineEdit_2.setText(lats_longs[1])
        self.lineEdit_3.setText(lats_longs[2])

        self.lineEdit_7.setText(str(angles[0]))
        self.lineEdit_8.setText(str(angles[1]))
        self.lineEdit_9.setText(str(angles[2]))

        self.lineEdit_6.setText(trans_lats_longs)

        

        
        lat_min = min(lats)-.00167
        lon_min = min(longs)-.00187
        lat_max = max(lats)+.00167
        lon_max = max(longs)+.00187
       

        # 30.62550842898528, -96.3353954198505

        # 30.623668922074334, -96.33266485523458

        
        rec1 = from_latlon(latitude=  lats[0], longitude = longs[0])
        rec2 = from_latlon(latitude = lats[1], longitude = longs[1])
        rec3 = from_latlon(latitude = lats[2], longitude = longs[2])

        minpoint = from_latlon(latitude= lat_min, longitude= lon_min)
        maxpoint = from_latlon(latitude=lat_max, longitude=lon_max)

        print(rec1)
        print(rec2)
        print(rec3)

        print(minpoint)
        print(maxpoint)

        newrec1 = (rec1[0] - minpoint[0], rec1[1] - minpoint[1])
        newrec2 = (rec2[0] - minpoint[0], rec2[1] - minpoint[1])
        newrec3 = (rec3[0] - minpoint[0], rec3[1] - minpoint[1])

        grid_size = (maxpoint[0] - minpoint[0], maxpoint[1]-minpoint[1])
        print(grid_size)


        print("Receiver 1", "X position: ", round(newrec1[0],5), "Y position: ", round(newrec1[1],5))
        print("Receiver 2", "X position: ", round(newrec2[0],5), "Y position: ", round(newrec2[1],5))
        print("Receiver 3", "X position: ", round(newrec3[0],5), "Y position: ", round(newrec3[1],5))

        
        
        
        
        # lat_min, lon_min = (48.848, 2.295)
        # lat_max, lon_max = (48.852, 2.305)
        API_KEY = "b8WjT8oKxjhu9w0mBYjE"
        image = satellite_images.query((lat_min, lon_min), (lat_max, lon_max), key=API_KEY, resolution="auto")
        im = Image.fromarray(image)
        im.save('background.jpg')

        pixmap = QPixmap('background.jpg')
        self.label_10.setPixmap(pixmap)
        

        pixmap2 = QPixmap('imageedit_2_9214147233.png')
        
        self.label_11.move(newrec1[0]+25, newrec1[1]-120)
        
        self.label_11.setPixmap(pixmap2)
        self.label_12.move(newrec2[0]+50, newrec2[1]-90)
        #self.label_12.move(20, -80)
        
        self.label_12.setPixmap(pixmap2)
        self.label_13.move(newrec3[0]+20, newrec3[1]-80)
        
        self.label_13.setPixmap(pixmap2)

        #min is 20,-80
        #max is 521, 421

        